### ISSUE TITLE
Exploding loss

### ISSUE THREAD

**Issue by khramtsova** [ThomasRobertFr/hybridnet#1]
Hi Thomas,

Thank you for your code! 

I'm trying to reproduce the results from your paper, and I noticed that the autoencoder with ResNet shake-shake is very unstable.
I ran the training several times, and the classification loss can randomly explode, and it is not always recovers to the same stage (see the graphs below with 3 trainings). I presume it's due to the gradient explosion, but I'm not sure what's causing it.

Any ideas on how to solve it? Did you experience the same unstable behavior? 

I'm using cifar_shakeshake26_hybrid for CIFAR10 with 2000 labeled images with "ae" as an architecture type.

![loss](https://user-images.githubusercontent.com/24212521/105455658-97d16400-5ccf-11eb-8de1-5d83f6435a7c.png)

![acc](https://user-images.githubusercontent.com/24212521/105455623-85efc100-5ccf-11eb-9f7d-734d68875b45.png)

**Comment by ThomasRobertFr** [comment]
Hi, I don't remember having big problems with exploding losses but these experiments dates back years ago so I might have just forgotten if I had those issues and how I solved them.

What can happen is that one loss is taking the lead over the others. For example the reconstruction loss destroys the work of the classification loss. What I would do is look at the different losses and check which ones are diverging and which ones are not.

Then, this can be solved by tuning the different loss weights and by using the schedulings on the lambdas. By default the reconstruction loss starts alone to initialize a reasonable auto-encoder before we start learning classification and both losses learn to work together.

I don't know if you changed something in the code but I know my experiments were quite stable toward changes in loss weights without divergence.

Good luck on your experiments, SSL is not an easy experimental setup :)
